### ISSUE TITLE
JavaScript errors and EOFError with DataVoyager.

### ISSUE THREAD

**Issue by braamvandyk** [queryverse/DataVoyager.jl#20]
I am running Julia v1.1.1 on Windows 10, with all packages updated to latest versions as of today (28 May 2019). The example code:
```
julia> using FileIO, CSVFiles, Query, DataVoyager

julia> v = load("Data.csv") |> Voyager()
```

results in two JavaScript errors popping up
```
Uncaught Exection:
Error: connect ENOENT \\.\pipe\juliaelectron-13864-1
   at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1113:14)
```
and 
```
Uncaught Exection:
Error: connect ENOENT \\.\pipe\juliaelectron-sysnotify-13864-1
   at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1113:14)
```
and in the REPL the following error
```
ERROR: EOFError: read end of file
Stacktrace:
 [1] unsafe_read(::Base.PipeEndpoint, ::Ptr{UInt8}, ::UInt64) at .\iobuffer.jl:165
 [2] unsafe_read at .\io.jl:585 [inlined]
 [3] macro expansion at .\gcutils.jl:87 [inlined]
 [4] read! at .\io.jl:597 [inlined]
 [5] Electron._Application{Electron.Window}() at C:\Users\vdykb\.julia\packages\Electron\wL84D\src\Electron.jl:136
 [6] Voyager() at C:\Users\vdykb\.julia\packages\DataVoyager\7x2Tx\src\DataVoyager.jl:20
 [7] top-level scope at none:0
```

I have verified that the file is read successfully. The error only comes in passing the data to Voyager(). I also tried converting to a DataFrame and passing that, but the results are similar.

I am more than happy to run any tests. I can also test this on other machines, if that would help.

**Comment by braamvandyk** [comment]
An update: I did a complete reinstall of Julia. As of 2 minutes ago, the following works:

```
julia> using RDatasets, DataVoyager

julia> cars = RDatasets.dataset("datasets", "cars")
50×2 DataFrame
<snip>

julia> Voyager(cars)

Voyager(Electron.Window(Application(Base.PipeEndpoint(Base.Libc.WindowsRawSocket(0x000000000000039c) open, 0 bytes waiting), Process(`'C:\Users\vdykb\.julia\packages\Electron\wL84D\src\..\deps\electron\electron.exe' 'C:\Users\vdykb\.julia\packages\Electron\wL84D\src\main.js' '\\.\pipe\juliaelectron-4000-1' '\\.\pipe\juliaelectron-sysnotify-4000-1' u52+4LrD4W8GOxrK7cW2KC2o4NYlnDWbqKHyJgs6CNWn25A262SDoZDiUHYf1xa3OJiDfxUQuu6TkLrUEpHQ9ZF9WsQZivVXqvvR/ms5wCXMUfEo11QYhJ0uBc5TufKwa7s7sL+QE7m40+BOruQXuLbo/4C+R/MRBzH6r33JcPs=`, ProcessRunning), [1 window]), 1, true, Channel{Any}(sz_max:128,sz_curr:0)))
```

I have no idea what caused the problem, but it seems to be on my side. Apologies if this caused undue effort for yourself.
